diabcontrol/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^patients/', include('patients.urls', namespace='patients')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^msg/', include('msg.urls', namespace='msg')),
    url(r'^reports/', include('reports.urls', namespace='reports')),

    url(r'^api/', include('rest_api.urls', namespace='rest_api')),

    url(r'^$', login_required(TemplateView.as_view(template_name='base.html'))),

    url('', include('social_django.urls', namespace='social'))
]

invitations/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from invitations.views import InvitationIndex, InviteFormView, AcceptFormView

urlpatterns = [
    url('^index/$', login_required(InvitationIndex.as_view()), name='index'),
    url('^invite/$', login_required(InviteFormView.as_view()), name='invite'),
    url('^accept/$', login_required(AcceptFormView.as_view()), name='accept'),
]

msg/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from msg.views import MessagesGroupsView, DetailsView

urlpatterns = [
    url('^$', login_required(MessagesGroupsView.as_view()), name='list'),
    url('^details/(?P<user_id>\d+)', login_required(DetailsView.as_view()), name='details')
]

invitations/models.py
from django.conf import settings
from django.db import models


class InvitationManager(models.Manager):
    def get_active(self, doctor):
        qs = self.all().filter(
            doctor=doctor,
            is_accepted=True,
        )

        return qs


class Invitation(models.Model):
    timestamp = models.DateTimeField(auto_now=True)
    doctor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='doctor_invitations'
    )
    patient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='patient_invitations'
    )
    is_accepted = models.BooleanField(default=False)

    objects = InvitationManager()

invitations/views.py
from django import forms
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView

from invitations.models import Invitation
from patients.models import Relationship


class InvitationIndex(ListView):
    template_name = 'invitations/index.html'
    model = Invitation


class InviteForm(forms.Form):
    doctor = forms.ChoiceField(required=True)


class InviteFormView(FormView):
    form_class = InviteForm
    template_name = 'invitations/invite.html'
    success_url = reverse_lazy("invitations:index")

    def get_form(self, form_class=None):
        form = super(InviteFormView, self).get_form(form_class)

        all_doctors = User.objects.filter(groups__name__exact='Doctor')
        all_doctors_ids = set([d.id for d in all_doctors])

        my_current_inv = Invitation.objects.filter(patient=self.request.user)
        my_current_inv = set([i.doctor.id for i in my_current_inv])

        my_doctors_relations = Relationship.objects.filter(patient=self.request.user)
        my_doctors_ids = set([r.doctor.id for r in my_doctors_relations])

        av_doctors_its = all_doctors_ids - my_doctors_ids - my_current_inv

        available_doctors = User.objects.filter(
            id__in=av_doctors_its
        )

        form.fields['doctor'].choices = (
            (doctor.id, doctor.get_full_name())
            for doctor in available_doctors
        )

        return form

    def form_valid(self, form):
        Invitation.objects.create(
            doctor_id=form.data['doctor'],
            patient_id=self.request.user.id
        )
        return super(InviteFormView, self).form_valid(form)


class AcceptForm(forms.Form):
    invitation = forms.TextInput()


class AcceptFormView(FormView):
    form_class = AcceptForm
    template_name = 'invitations/index.html'
    success_url = reverse_lazy("invitations:index")

    def form_valid(self, form):
        invitation = Invitation.objects.get(
            pk=form.data['invitation']
        )
        invitation.is_accepted = True
        invitation.save()
        Relationship.objects.create(
            doctor=invitation.doctor,
            patient=invitation.patient
        )
        return super(AcceptFormView, self).form_valid(form)

templates/invitations/index.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
    <h1 class="page-header">My invitations</h1>
    {% if is_doctor %}
    <table class="table">
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>Patient</th>
                <th>Is accepted</th>
                <th>Accept</th>
            </tr>
        </thead>
        <tbody>
            {% for invitation in object_list %}
                {% if invitation.doctor == request.user %}
                <tr>
                    <td>{{ invitation.timestamp }}</td>
                    <td>{{ invitation.patient.get_full_name }}</td>
                    <td>{% bootstrap_icon invitation.is_accepted|yesno:'ok-sign,question-sign' %}</td>
                    <td>
                        {% if not invitation.is_accepted %}
                            <form method="post" action="{% url 'invitations:accept' %}">
                                {% csrf_token %}
                                <input type="hidden" name="invitation" value="{{ invitation.id }}">
                                <input type="submit" class="btn-link" value="Accept">
                            </form>
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <table class="table">
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>Doctor</th>
                <th>Is accepted</th>
            </tr>
        </thead>
        <tbody>
            {% for invitation in object_list %}
                {% if invitation.patient == request.user %}
                <tr>
                    <td>{{ invitation.timestamp }}</td>
                    <td>{{ invitation.doctor.get_full_name }}</td>
                    <td>{{ invitation.is_accepted|yesno }}</td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

templates/invitations/invite.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
    <form action="{% url 'invitations:invite' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            Invite
        </button>
    {% endbuttons %}
  </form>
{% endblock %}