diabcontrol/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^patients/', include('patients.urls', namespace='patients')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^msg/', include('msg.urls', namespace='msg')),
    url(r'^reports/', include('reports.urls', namespace='reports')),

    url(r'^api/', include('rest_api.urls', namespace='rest_api')),

    url(r'^$', login_required(TemplateView.as_view(template_name='base.html'))),

    url('', include('social_django.urls', namespace='social'))
]

msg/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from msg.views import MessagesGroupsView, DetailsView

urlpatterns = [
    url('^$', login_required(MessagesGroupsView.as_view()), name='list'),
    url('^details/(?P<user_id>\d+)', login_required(DetailsView.as_view()), name='details')
]

patients/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from patients.views import PatientIndex, PatientDetails, DailyResultsDetails, MonthlyResultsDetails, \
    YearlyResultsDetails

urlpatterns = [
    url('^index/$', login_required(PatientIndex.as_view()), name='index'),
    url('^details/(?P<pk>\d+)/$', login_required(PatientDetails.as_view()), name='details'),

    url('^details/(?P<pk>\d+)/results/daily/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})$',
        login_required(DailyResultsDetails.as_view()), name='daily_results'),
    url('^details/(?P<pk>\d+)/results/monthly/(?P<year>\d{4})/(?P<month>\d{1,2})$',
        login_required(MonthlyResultsDetails.as_view()), name='monthly_results'),
    url('^details/(?P<pk>\d+)/results/yearly/(?P<year>\d{4})$',
        login_required(YearlyResultsDetails.as_view()), name='yearly_results'),
]

patients/models.py
from django.conf import settings
from django.db import models


class RelationshipManager(models.Manager):
    def get_doctor_relations(self, doctor):
        relations = self.filter(
            doctor=doctor
        )

        return [r.patient for r in relations]

    def get_patient_relations(self, patient):
        relations = self.filter(
            patient=patient
        )

        return [r.doctor for r in relations]


class Relationship(models.Model):
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='patients')
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='doctors')

    objects = RelationshipManager()

patients/views.py
from datetime import date, timedelta
from calendar import monthrange

from django import forms
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, FormView

from msg.models import Message
from patients.models import Relationship
from reports.models import ReportData


class PatientIndex(ListView):
    model = Relationship
    template_name = 'patients/index.html'

    def get_queryset(self):
        queryset = super(PatientIndex, self).get_queryset()
        return queryset.filter(doctor=self.request.user)


class MessageForm(forms.Form):
    content = forms.Field(required=True)


class PatientDetails(FormView):
    template_name = 'patients/details/base.html'
    form_class = MessageForm
    patient = None

    def dispatch(self, request, *args, **kwargs):
        self.patient = get_object_or_404(
            User,
            pk=self.kwargs['pk'],
            groups__name__exact='Patient',
        )
        return super(PatientDetails, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy(
            'patients:details',
            kwargs={'pk': self.patient.id}
        )

    def form_valid(self, form):
        Message.objects.create(
            sender=self.request.user,
            receiver=self.patient,
            content=form.data['content'],
        )
        return super(PatientDetails, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PatientDetails, self).get_context_data(**kwargs)
        context['patient'] = self.patient
        context['reports'] = self.patient.report_set.all()
        context['messages'] = Message.objects.conversations(
            self.request.user, self.patient
        )
        return context


class PatientDateMixin(object):
    patient = None
    current_date = None

    def dispatch(self, request, *args, **kwargs):
        self.patient = get_object_or_404(
            User,
            pk=kwargs.pop('pk', 0),
            groups__name__exact='Patient',
        )
        try:
            self.current_date = date(
                int(kwargs.pop('year')),
                int(kwargs.pop('month', 1)),
                int(kwargs.pop('day', 1)),
            )
        except ValueError:
            raise Http404
        return super(PatientDateMixin, self).dispatch(request, *args, **kwargs)


class ResultsDetails(PatientDateMixin, TemplateView):

    def get_context_data(self, **kwargs):
        context = super(ResultsDetails, self).get_context_data(**kwargs)
        context['date'] = self.current_date
        context['patient'] = self.patient

        context.update(self.get_activity_context())
        context.update(self.get_nutrition_context())
        context.update(self.get_glucose_context())

        return context

    def get_activity_context(self):
        return {}

    def get_nutrition_context(self):
        return {}

    def get_glucose_context(self):
        return {}


class DailyResultsDetails(ResultsDetails):
    template_name = 'patients/results_daily.html'

    def get_context_data(self, **kwargs):
        context = super(DailyResultsDetails, self).get_context_data(**kwargs)
        context['date'] = self.current_date
        context['patient'] = self.patient

        context.update(self.get_activity_context())
        context.update(self.get_nutrition_context())
        context.update(self.get_glucose_context())

        return context

    def get_activity_context(self):
        steps_data = ReportData.objects.filter(
            type='steps',
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )

        climbed_data = ReportData.objects.filter(
            type='flights_climbed',
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )

        heartrate_data_act = ReportData.objects.filter(
            type='heart_rate',
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )

        heartrate_data_avg = ReportData.objects.filter(
            type='heart_rate',
            patient_id=self.patient.id,
            datetime__month=(self.current_date.replace(day=1) - timedelta(days=1)).month,
        )

        if heartrate_data_avg:
            avg_prev_hr = sum(
                [data.value for data in heartrate_data_avg]
            )/len(heartrate_data_avg)
        else:
            avg_prev_hr = 0

        if heartrate_data_act:
            actual_avg_heartrate = sum(
                [data.value for data in heartrate_data_act]
            )
        else:
            actual_avg_heartrate = 0

        hr_status = 'default'

        if avg_prev_hr * 1.3 >= actual_avg_heartrate \
                or avg_prev_hr * 0.7 <= actual_avg_heartrate:
            hr_status = 'warning'
        if avg_prev_hr * 1.5 >= actual_avg_heartrate \
                or avg_prev_hr * 0.5 <= actual_avg_heartrate:
            hr_status = 'danger'

        return {
            'steps': sum([data.value for data in steps_data]),
            'flights_climbed': sum([data.value for data in climbed_data]),
            'heart_rate': sum([data.value for data in heartrate_data_act]),
            'avg_prev_hr': avg_prev_hr,
            'hr_status': hr_status if avg_prev_hr else 'default'
        }

    def get_nutrition_context(self):
        fat_data = ReportData.objects.filter(
            type='fat',
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )

        protein_data = ReportData.objects.filter(
            type='protein',
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )

        carb_data = ReportData.objects.filter(
            type='carbohydrates',
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )

        return {
            'fat': sum([data.value for data in fat_data]),
            'protein': sum([data.value for data in protein_data]),
            'carbohydrates': sum([data.value for data in carb_data])
            }

    def get_glucose_context(self):
        glucose_data = ReportData.glucose_measurement.filter(
            patient_id=self.patient.id,
            datetime__day=self.current_date.day,
            datetime__month=self.current_date.month,
            datetime__year=self.current_date.year,
        )
        values = [data.value for data in glucose_data]
        min_glucose, max_glucose, avg_glucose = None, None, None

        if values:
            min_glucose = min(values)
            max_glucose = max(values)
            avg_glucose = sum(values) / len(values)

        status = 'default'
        if any(filter(lambda x: x < 60 or x > 139, values)):
            status = 'danger'
        elif any(filter(lambda x: x < 70 or x > 99, values)):
            status = 'warning'

        return {
            'glucose_min': min_glucose,
            'glucose_max': max_glucose,
            'glucose_avg': avg_glucose,
            'status': status
        }


class SummaryResultsDetails(ResultsDetails):

    def get_start_end_chunk(self):
        raise NotImplementedError()

    def get_chunks(self, list_data):
        chunks = [
            [
                data.value
                for data in list_data
                if data.datetime.day == day
                ]
            for day in range(*self.get_start_end_chunk())
            ]
        return [chunk for chunk in chunks if chunk]

    @property
    def glucose_data(self):
        raise NotImplementedError()

    def get_glucose_context(self):
        chunks = [
            [
                data.value
                for data in self.glucose_data
                if data.datetime.day == day
            ]
            for day in range(*self.get_start_end_chunk())
        ]
        chunks = [chunk for chunk in chunks if chunk]

        context = {}
        if not any(chunks):
            return context

        values = [data.value for data in self.glucose_data]
        context['values_per_day'] = dict(
            min=min(values),
            max=max(values),
        )

        values_avg = [sum(chunk) / (len(chunk) or 1) for chunk in chunks]
        context['values_per_month'] = dict(
            min=min(values_avg),
            max=max(values_avg),
            avg=sum(values_avg) / (len(values_avg) or 1),
        )

        return context

    @property
    def heartrate_data(self):
        raise NotImplementedError()

    def context_hr_data(self):
        chunks = self.get_chunks(self.heartrate_data)
        context = {}

        if not any(chunks):
            return context

        values = [data.value for data in self.heartrate_data]
        context['hr_val_per_day'] = dict(
            min=min(values),
            max=max(values),
        )

        values_avg = [sum(chunk) / (len(chunk) or 1) for chunk in chunks]
        context['hr_val_per_month'] = dict(
            min=min(values_avg),
            max=max(values_avg),
            avg=sum(values_avg) / (len(values_avg) or 1),
        )
        return context

    @property
    def climbed_data(self):

templates/patients/index.html
{% extends "base.html" %}

{% block content %}
    <h1 class="page-header">My patients</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
            {% for rel in object_list %}
                <tr>
                    <td class="email">
                        <a href="{% url 'patients:details' pk=rel.patient.id %}">
                            {{ rel.patient.email }}
                        </a>
                    </td>
                    <td class="fname">{{ rel.patient.first_name }}</td>
                    <td class="lname">{{ rel.patient.last_name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/patients/results_daily.html
{% extends "base.html" %}


{% block content %}
    <div class="page-header">
        <h1>Daily results <small> {{ date|date:"d F Y" }}</small></h1>
        <h2>{{ patient.get_full_name }}</h2>
    </div>
    <nav>
      <ul class="pager">
        <li class="previous">
            <a href="{% url 'patients:daily_results' patient.id date.year date.month date.day|add:"-1" %}">
                <span aria-hidden="true">&larr;</span> Previous</a>
        </li>
        <li class="next">
            <a href="{% url 'patients:daily_results' patient.id date.year date.month date.day|add:"1" %}">Next
                <span aria-hidden="true">&rarr;</span></a></li>
      </ul>
    </nav>

    <h2>Physical effort</h2>
    <div class="row">
        <div class="col-md-6">
              <canvas width="500" height="300" id="dailyHrChart"></canvas>
        </div>
        <div class="col-md-6">
            <dl class="dl-horizontal" style="margin: inherit;">
                <dt >Heart rate average of today:</dt>
                <dd class="text-uppercase text-{{ hr_status }}">{{ heart_rate }} BPM</dd>
                <dt>Heart rate average of previous month:</dt>
                <dd> {{ avg_prev_hr }} BPM</dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
              <canvas width="500" height="300" id="dailyStepsChart"></canvas>
        </div>
        <div class="col-md-6">
            <dl class="dl-horizontal" style="margin: inherit;">
                <dt>Steps:</dt>
                <dd>{{ steps }}</dd>
                <dt>Flights climbed</dt>
                <dd>{{ flights_climbed }} Floors</dd>
            </dl>
        </div>
    </div>

    <h2>Diet nutrition</h2>
    <div id="container" style="min-width: 310px; height: 400px; max-width: 500px; margin: 0 0" ></div>
    <div>
        <dl>
            <dt>Fat:</dt>
            <dd>{{ fat }} g</dd>
            <dt>Protein:</dt>
            <dd>{{ protein }} g</dd>
            <dt>Carbohydrates:</dt>
            <dd>{{ carbohydrates }} g</dd>
        </dl>
    </div>

    <h2>Glucose</h2>
    {% if status == 'danger' or status == 'warning' %}
        <p class="text-{{ status }} text-uppercase">You should take a look at this!</p>
    {% endif %}

    <div class="row">
        <div class="col-md-6">
              <canvas width="500" height="300" id="dailyGlucoseChart"></canvas>
        </div>
        <div class="col-md-6">
            <dl class="dl-horizontal" style="margin: inherit;">
                <dt>Daily average</dt>
                <dd>{{ glucose_avg }} mg/dL</dd>
                <dt>Daily minimum</dt>
                <dd>{{ glucose_min }} mg/dL</dd>
                <dt>Daily maximim</dt>
                <dd>{{ glucose_max }} mg/dL</dd>
                <dt>State</dt>
                <dd><p class="text-uppercase text-{{ status }}">{{ status }}</p></dd>
            </dl>
        </div>
    </div>

{% endblock %}


{% block scripts %}

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/glucose/daily/{{ date.year }}/{{ date.month }}/{{ date.day }}/', function(data) {
            var ctx = $("#dailyGlucoseChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/hr/daily/{{ date.year }}/{{ date.month }}/{{ date.day }}/', function(data) {
            var ctx = $("#dailyHrChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/steps/daily/{{ date.year }}/{{ date.month }}/{{ date.day }}/', function(data) {
            var ctx = $("#dailyStepsChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        window.macros = $.get('/api/patients/{{ patient.pk }}/charts/macros/daily/{{ date.year }}/{{ date.month }}/{{ date.day }}/');
    </script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script type="text/javascript">

        $(function () {
            window.macros.then(function (data) {
                Highcharts.chart('container', {
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false,
                        type: 'pie'
                    },
                    title: {
                        text: ''
                    },
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: true,
                                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                                style: {
                                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                                }
                            }
                        }
                    },
                    series: [{
                        name: 'Macro',
                        colorByPoint: true,
                        data: data.macros
                    }]
                });

            })
        });
    </script>
{% endblock %}

templates/patients/results_monthly.html
{% extends "base.html" %}


{% block content %}
    <div class="page-header">
        <h1>Monthly results <small> {{ date|date:"F Y" }}</small></h1>
        <h2>{{ patient.get_full_name }}</h2>
    </div>
    <nav>
      <ul class="pager">
        <li class="previous">
            <a href="{% url 'patients:monthly_results' patient.id date.year date.month|add:"-1" %}">
                <span aria-hidden="true">&larr;</span> Previous</a>
        </li>
        <li class="next">
            <a href="{% url 'patients:monthly_results' patient.id date.year date.month|add:"1" %}">Next
                <span aria-hidden="true">&rarr;</span></a></li>
      </ul>
    </nav>
    <h2>Physical effort</h2>
    {% include "patients/summary/heartRate.html" with chart_id="monthlyHrChart" %}
    {% include "patients/summary/climbed.html" with chart_id="monthlyClimbedChart"%}
    {% include "patients/summary/steps.html" with chart_id="monthlyStepsChart"%}

    <h2>Diet nutrition</h2>
    {% include "patients/summary/nutrition.html" with chart_id="container"%}

    {% include "patients/summary/glucose.html" with chart_id="monthlyGlucoseChart" %}

{% endblock %}


{% block scripts %}
    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/glucose/monthly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#monthlyGlucoseChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/hr/monthly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#monthlyHrChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/climbed/monthly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#monthlyClimbedChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/steps/monthly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#monthlyStepsChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        window.macros = $.get('/api/patients/{{ patient.pk }}/charts/macros/monthly/{{ date.year }}/{{ date.month }}/{{ date.day }}/');
    </script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script type="text/javascript">

        $(function () {
            window.macros.then(function (data) {
                Highcharts.chart('container', {
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false,
                        type: 'pie'
                    },
                    title: {
                        text: ''
                    },
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: true,
                                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                                style: {
                                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                                }
                            }
                        }
                    },
                    series: [{
                        name: 'Macro',
                        colorByPoint: true,
                        data: data.macros
                    }]
                });

            })
        });
    </script>

{% endblock %}

templates/patients/results_yearly.html
{% extends "base.html" %}


{% block content %}
    <div class="page-header">
        <h1>Yearly results <small> {{ date|date:"Y" }}</small></h1>
        <h2>{{ patient.get_full_name }}</h2>
    </div>
    <nav>
      <ul class="pager">
        <li class="previous">
            <a href="{% url 'patients:yearly_results' patient.id date.year|add:"-1" %}">
                <span aria-hidden="true">&larr;</span> Previous</a>
        </li>
        <li class="next">
            <a href="{% url 'patients:yearly_results' patient.id date.year|add:"1" %}">Next
                <span aria-hidden="true">&rarr;</span></a></li>
      </ul>
    </nav>

    <h2>Physical effort</h2>
        {% include "patients/summary/heartRate.html" with chart_id="yearlyHrChart" %}
        {% include "patients/summary/climbed.html" with chart_id="yearlyClimbedChart"%}
        {% include "patients/summary/steps.html" with chart_id="yearlyStepsChart"%}

    <h2>Diet nutrition</h2>
    {% include "patients/summary/nutrition.html" with chart_id="container"%}

    {% include "patients/summary/glucose.html" with chart_id="yearlyGlucoseChart" %}

{% endblock %}


{% block scripts %}
    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/glucose/yearly/{{ date.year }}/', function(data) {
            var ctx = $("#yearlyGlucoseChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/hr/yearly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#yearlyHrChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/climbed/yearly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#yearlyClimbedChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        $.get('/api/patients/{{ patient.pk }}/charts/steps/yearly/{{ date.year }}/{{ date.month }}/', function(data) {
            var ctx = $("#yearlyStepsChart").get(0).getContext("2d");
            new Chart(ctx).Line(data);
        });
    </script>

    <script type="text/javascript">
        window.macros = $.get('/api/patients/{{ patient.pk }}/charts/macros/yearly/{{ date.year }}/{{ date.month }}/{{ date.day }}/');
    </script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script type="text/javascript">

        $(function () {
            window.macros.then(function (data) {
                Highcharts.chart('container', {
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false,
                        type: 'pie'
                    },
                    title: {
                        text: ''
                    },
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: true,
                                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                                style: {
                                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                                }
                            }
                        }
                    },
                    series: [{
                        name: 'Macro',
                        colorByPoint: true,
                        data: data.macros
                    }]
                });

            })
        });
    </script>

{% endblock %}