diabcontrol/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^patients/', include('patients.urls', namespace='patients')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^msg/', include('msg.urls', namespace='msg')),
    url(r'^reports/', include('reports.urls', namespace='reports')),

    url(r'^api/', include('rest_api.urls', namespace='rest_api')),

    url(r'^$', login_required(TemplateView.as_view(template_name='base.html'))),

    url('', include('social_django.urls', namespace='social'))
]

msg/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from msg.views import MessagesGroupsView, DetailsView

urlpatterns = [
    url('^$', login_required(MessagesGroupsView.as_view()), name='list'),
    url('^details/(?P<user_id>\d+)', login_required(DetailsView.as_view()), name='details')
]

templates/messages/details.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
    </tr>
    </thead>
    <tbody>
    {% for msg in object_list %}

      <tr>
        <td>{{ msg.content }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/messages/list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
    </tr>
    </thead>
    <tbody>
    {% for msg in object_list %}

      <tr>
        <td><a href="{% url 'msg:details' msg.doctor.id %}">{{ msg.doctor }} - {{ msg.patient }}</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}